name: i_am_poor
description: A new Flutter application.

publish_to:


version: 1.0.0+1

environment:
  sdk:

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - images/coal.jpg


